### ISSUE TITLE
practica 

### ISSUE THREAD

**Issue by Erick-3as** [SistemasTecTlaxiaco/practica-de-conjuntos-eq-erick-yanet-lourdes-1as#1]
[PRÁCTICA OPERACIONES CON CONJUNTOS-MARIADELOURDES-JANET-ERICK.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-conjuntos-eq-erick-yanet-lourdes-1as/files/7297960/PRACTICA.OPERACIONES.CON.CONJUNTOS-MARIADELOURDES-JANET-ERICK.pdf)

**Comment by RicardoMtzSts** [comment]
Portada ''excelente''; Procedimientos ''excelente''; Resultados y conclusiones ''excelente''.

**Comment by RicardoMtzSts** [comment]
Portada (excelente) contiene todos los datos requeridos 25 puntos
Procedimiento Les faltó describir el procedimiento de cada uno de los ejercicios hasta el como llegaron al resultado y en unos ejercicios esta mal el resultado ya que debe ser vacío 15 puntos
Figuras, ilustraciones y fotos ( Excelente) Contiene las figuras requeridas en la rubrica 25 puntos
Resultados y conclusiones (Excelente) cumple con todos los requisitos 25 puntos
Total: 90/100          Calificación: 18% / 20%
Calificado por: Ricardo Martínez Santos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
